# Your presentation title
title: Apprentice boot-camp - Fundamentals 1

remote_theme: autotraderuk/jekyll-revealjs@v2.0.0
plugins:
  - jekyll-remote-theme

# The Reveal theme
reveal_theme: league.css

# The Reveal transition
reveal_transition: default

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: assets/reveal.js/css/theme/ 

# Additional custom CSS paths
extra_css: 

# Custom CSS for highlighting (defaults to reveal.js/lib/css/zenburn.css)
highlight_style_sheet: 

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options:
  slideNumber: 'c/t'

# Additional reveal.js dependencies
reveal_dependencies: 

# Reveal.js subdirectory
reveal_path: assets/reveal.js/

# Don't change anything below
markdown: redcarpet
highlighter: rouge
markdown_ext: ignoreme
